My Project: algorithm.cpp File Reference
algorithm.cpp File Reference
#include "types.h"
#include "algorithm.h"
#include <math.h>
#include "debug.h"
Functions
void SolveEquation (const Coeffs *ptr_coefficients, Solutions *ptr_solutions)
double CalculateDiscriminant (const Coeffs *ptr_coefficients)
bool AreEqual (double number_1, double number_2)
Function Documentation
AreEqual()
bool AreEqual (double number_1, double number_2)
Determines if two numbers are equal
Parameters
number_1 the first number
number_2 the second number
Definition at line 119 of file algorithm.cpp.
{
    static const double kE = 1e-4;
    return fabs(number_1 - number_2) < kE;
}
Referenced by SolveEquation().
CalculateDiscriminant()
double CalculateDiscriminant (const Coeffs * ptr_coefficients)
Calculates the discriminant, returns its value based on the values of the coefficients of the quadratic equation
Parameters
ptr_coeffients pointer to the structure with the coefficients of the quadratic equation
Definition at line 79 of file algorithm.cpp.
{
    CHECK(ptr_coefficients);
    return ptr_coefficients->b * ptr_coefficients->b - 4 * ptr_coefficients->a * ptr_coefficients->c;
}
References Coeffs::a, Coeffs::b, Coeffs::c, and CHECK.
Referenced by SolveEquation().
SolveEquation()
void SolveEquation (const Coeffs * ptr_coefficients, Solutions * ptr_solutions)
Solves a quadratic equation. Returns a constant corresponding to the number of roots.
Parameters
ptr_coefficients pointer to a structure with quadratic equation coefficients
ptr_solutions pointer to a structure with roots of a quadratic equation
Note
If two roots are present, first root is greater.
See also
types.h
Definition at line 30 of file algorithm.cpp.
{
    CHECK(ptr_coefficients);
    CHECK(ptr_solutions);
    double discriminant = CalculateDiscriminant(ptr_coefficients);
    if (discriminant < 0)
    {
        ptr_solutions->roots_count =  kZeroRoots;
        return;
    }
    else if (!AreEqual(ptr_coefficients->a, 0))
    {
        ptr_solutions->roots_count = SolveQuadCase(ptr_coefficients,
                                                   discriminant,
                                                   ptr_solutions);
        return;
    }
    else
    {
        if (!AreEqual(ptr_coefficients->b, 0))
        {
            ptr_solutions->roots_count = SolveLinearCase(ptr_coefficients,
                                                         ptr_solutions);
            return;
        }
        else
        {
            if (!AreEqual(ptr_coefficients->c, 0))
            {
                ptr_solutions->roots_count = kZeroRoots;
                return;
            }
            else
            {
                ptr_solutions->roots_count =  kInfRoots;
                return;
            }
        }
    }
}
References Coeffs::a, AreEqual(), Coeffs::b, Coeffs::c, CalculateDiscriminant(), CHECK, kInfRoots, kZeroRoots, and Solutions::roots_count.