Kvadratka: input.cpp File Reference
input.cpp File Reference
#include <string.h>
#include "types.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "input.h"
#include "debug.h"
#include "algorithm.h"
#include "output.h"
#include "test.h"
Functions
InputResults GetInput (FILE *ptr_file, Coeffs *ptr_coefficients)
InputResults ConvertBuf (char *buf, Coeffs *ptr_coefficients)
InputResults ConvertBufToCoeffs (char *buf, Coeffs *ptr_coefficients)
Function Documentation
ConvertBuf()
InputResults ConvertBuf (char * buf, Coeffs * ptr_coefficients)
Checks whether the string written in the buffer is a command. Outputs the constant corresponding to the command.
Parameters
buf buffer
ptr_coeffients pointer to the coefficient structure
Note
if there are three coefficients in the buffer, they are written to the structure pointed to by ptr_coeffients.
See also
ConvertBufToCoeffs() input.h
Definition at line 81 of file input.cpp.
{
    CHECK(buf);
    CHECK(ptr_coefficients);
    char command[kMaxBuf] = {0};
    command[0] = '\0';
    bool is_one_word = CutSpaces(buf, command);
    if (is_one_word)
    {
        for (int i = 0; i < kCommandArraySize; ++i)
        {
            if (strcmp(command, CommandArray[i].command_name) == 0)
            {
                return CommandArray[i].result;
            }
        }
    }
    return ConvertBufToCoeffs(buf,
                              ptr_coefficients);
}
References CommandArray, ConvertBufToCoeffs(), kCommandArraySize, and Command::result.
Referenced by GetInput().
ConvertBufToCoeffs()
InputResults ConvertBufToCoeffs (char * buf, Coeffs * ptr_coefficients)
Writes the values of the coefficients specified in the buffer to the coefficient structure
Parameters
buf buffer
ptr_coeffients pointer to the structure of coefficients
Note
if coefficients are written incorrectly in the buffer, returns the kInputError error
See also
input.h
Definition at line 108 of file input.cpp.
{
    CHECK(buf);
    CHECK(ptr_coefficients);
    char *number_end = nullptr;
    ptr_coefficients->a = strtod(buf, &number_end);
    if (buf != number_end)
    {
        buf = number_end;
        ptr_coefficients->b = strtod(buf, &number_end);
    }
    if (buf != number_end)
    {
        buf = number_end;
        ptr_coefficients->c = strtod(buf, &number_end);
    }
    while (isspace(*number_end))
    {
        ++number_end;
    }
    if (*number_end == '\0' && buf[0] != '\0')
    {
        return kInputSuccess;
    }
    else
    {
        return kInputError;
    }
}
References Coeffs::a, Coeffs::b, Coeffs::c, kInputError, and kInputSuccess.
Referenced by ConvertBuf().
GetInput()
InputResults GetInput (FILE * ptr_file, Coeffs * ptr_coefficients)
Writes the characters read from the file to the buffer, outputs a constant corresponding to the command written to the buffer.
Parameters
ptr_file pointer to a readable file.
ptr_coeffients pointer to the structure of coefficients.
Note
if there are three coefficients in the buffer, they are written to the structure pointed to by ptr_coeffients.
See also
ConvertBuf() ConvertBufToCoeffs()input.h
Definition at line 22 of file input.cpp.
{
    CHECK(ptr_coefficients);
    CHECK(ptr_file);
    static char buf[kMaxBuf] = {0};
    buf[0] = '\0';
    int i = 0;
    int c = 0;
    if (ferror(ptr_file))
    {
        return kInputFileError;
    }
    bool BufferOverflowStatus = false;
    while ((c = getc(ptr_file)) != '\n')
    {
        if (i < kMaxBuf - 1)
        {
            if (c != EOF)
            {
                buf[i++] = (char) c;
            }
            else
            {
                return kEofError;
            }
        }
        else
        {
            BufferOverflowStatus = true;
        }
    }
    if (buf[0] == '\0')
    {
        return kZeroStr;
    }
    if (BufferOverflowStatus)
    {
        return kBufferOverflowError;
    }
    if (i > 0)
    {
        buf[i] = '\0';
    }
    return ConvertBuf(buf, ptr_coefficients);
}
References ConvertBuf(), kBufferOverflowError, kEofError, kInputFileError, and kZeroStr.